
services:
  gophermart:
    build: .
    ports:
      - 8080:8080
    environment:
      - CONFIG_PATH=/config.yaml
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=gophermart
    volumes:
      - ./config-example.yaml:/config.yaml:ro
      - ./migration:/app/migration:ro
    depends_on:
      - postgres
    networks:
      - gophermart

  postgres:
    image: postgres:18
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=gophermart
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - gophermart-data:/var/lib/postgresql/data
    networks:
      - gophermart


  pgadmin:
    image: dpage/pgadmin4:9.15
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.org"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - gophermart-pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - gophermart

volumes:
  gophermart-data:
  gophermart-pgadmin-data:

networks:
  gophermart:
    driver: bridge