// Code generated by MockGen. DO NOT EDIT.
// Source: balance.go
//
// Generated by this command:
//
//	mockgen -source=balance.go -destination=mock_balance_test.go -package=service
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	model "github.com/paulwwyvern/gophermart/internal/model"
	decimal "github.com/shopspring/decimal"
	gomock "go.uber.org/mock/gomock"
)

// MockBalanceRepository is a mock of BalanceRepository interface.
type MockBalanceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceRepositoryMockRecorder
	isgomock struct{}
}

// MockBalanceRepositoryMockRecorder is the mock recorder for MockBalanceRepository.
type MockBalanceRepositoryMockRecorder struct {
	mock *MockBalanceRepository
}

// NewMockBalanceRepository creates a new mock instance.
func NewMockBalanceRepository(ctrl *gomock.Controller) *MockBalanceRepository {
	mock := &MockBalanceRepository{ctrl: ctrl}
	mock.recorder = &MockBalanceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceRepository) EXPECT() *MockBalanceRepositoryMockRecorder {
	return m.recorder
}

// AddUserBalanceByID mocks base method.
func (m *MockBalanceRepository) AddUserBalanceByID(ctx context.Context, userId int64, add decimal.Decimal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserBalanceByID", ctx, userId, add)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserBalanceByID indicates an expected call of AddUserBalanceByID.
func (mr *MockBalanceRepositoryMockRecorder) AddUserBalanceByID(ctx, userId, add any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserBalanceByID", reflect.TypeOf((*MockBalanceRepository)(nil).AddUserBalanceByID), ctx, userId, add)
}

// AddUserWithdrawnByID mocks base method.
func (m *MockBalanceRepository) AddUserWithdrawnByID(ctx context.Context, userID int64, add decimal.Decimal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserWithdrawnByID", ctx, userID, add)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserWithdrawnByID indicates an expected call of AddUserWithdrawnByID.
func (mr *MockBalanceRepositoryMockRecorder) AddUserWithdrawnByID(ctx, userID, add any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserWithdrawnByID", reflect.TypeOf((*MockBalanceRepository)(nil).AddUserWithdrawnByID), ctx, userID, add)
}

// BeginTx mocks base method.
func (m *MockBalanceRepository) BeginTx(ctx context.Context) (context.Context, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockBalanceRepositoryMockRecorder) BeginTx(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockBalanceRepository)(nil).BeginTx), ctx)
}

// CommitTx mocks base method.
func (m *MockBalanceRepository) CommitTx(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitTx", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitTx indicates an expected call of CommitTx.
func (mr *MockBalanceRepositoryMockRecorder) CommitTx(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitTx", reflect.TypeOf((*MockBalanceRepository)(nil).CommitTx), ctx)
}

// CreateWithdrawal mocks base method.
func (m *MockBalanceRepository) CreateWithdrawal(ctx context.Context, withdrawal *model.Withdrawal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithdrawal", ctx, withdrawal)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWithdrawal indicates an expected call of CreateWithdrawal.
func (mr *MockBalanceRepositoryMockRecorder) CreateWithdrawal(ctx, withdrawal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithdrawal", reflect.TypeOf((*MockBalanceRepository)(nil).CreateWithdrawal), ctx, withdrawal)
}

// GetUserBalanceByID mocks base method.
func (m *MockBalanceRepository) GetUserBalanceByID(ctx context.Context, userId int64) (*model.UserBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserBalanceByID", ctx, userId)
	ret0, _ := ret[0].(*model.UserBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserBalanceByID indicates an expected call of GetUserBalanceByID.
func (mr *MockBalanceRepositoryMockRecorder) GetUserBalanceByID(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserBalanceByID", reflect.TypeOf((*MockBalanceRepository)(nil).GetUserBalanceByID), ctx, userId)
}

// GetWithdrawalsByUserID mocks base method.
func (m *MockBalanceRepository) GetWithdrawalsByUserID(ctx context.Context, userID int64) ([]*model.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdrawalsByUserID", ctx, userID)
	ret0, _ := ret[0].([]*model.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithdrawalsByUserID indicates an expected call of GetWithdrawalsByUserID.
func (mr *MockBalanceRepositoryMockRecorder) GetWithdrawalsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdrawalsByUserID", reflect.TypeOf((*MockBalanceRepository)(nil).GetWithdrawalsByUserID), ctx, userID)
}

// RollbackTx mocks base method.
func (m *MockBalanceRepository) RollbackTx(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackTx", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RollbackTx indicates an expected call of RollbackTx.
func (mr *MockBalanceRepositoryMockRecorder) RollbackTx(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackTx", reflect.TypeOf((*MockBalanceRepository)(nil).RollbackTx), ctx)
}
