// Code generated by MockGen. DO NOT EDIT.
// Source: order.go
//
// Generated by this command:
//
//	mockgen -source=order.go -destination=mock_order_test.go -package=service
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	model "github.com/paulwwyvern/gophermart/internal/model"
	decimal "github.com/shopspring/decimal"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderRepository is a mock of OrderRepository interface.
type MockOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryMockRecorder
	isgomock struct{}
}

// MockOrderRepositoryMockRecorder is the mock recorder for MockOrderRepository.
type MockOrderRepositoryMockRecorder struct {
	mock *MockOrderRepository
}

// NewMockOrderRepository creates a new mock instance.
func NewMockOrderRepository(ctrl *gomock.Controller) *MockOrderRepository {
	mock := &MockOrderRepository{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepository) EXPECT() *MockOrderRepositoryMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockOrderRepository) CreateOrder(ctx context.Context, userId int64, number string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, userId, number)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockOrderRepositoryMockRecorder) CreateOrder(ctx, userId, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockOrderRepository)(nil).CreateOrder), ctx, userId, number)
}

// GetOrdersByUserID mocks base method.
func (m *MockOrderRepository) GetOrdersByUserID(ctx context.Context, userId int64) ([]*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrdersByUserID", ctx, userId)
	ret0, _ := ret[0].([]*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrdersByUserID indicates an expected call of GetOrdersByUserID.
func (mr *MockOrderRepositoryMockRecorder) GetOrdersByUserID(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdersByUserID", reflect.TypeOf((*MockOrderRepository)(nil).GetOrdersByUserID), ctx, userId)
}

// MockOrderAccrualRepository is a mock of OrderAccrualRepository interface.
type MockOrderAccrualRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderAccrualRepositoryMockRecorder
	isgomock struct{}
}

// MockOrderAccrualRepositoryMockRecorder is the mock recorder for MockOrderAccrualRepository.
type MockOrderAccrualRepositoryMockRecorder struct {
	mock *MockOrderAccrualRepository
}

// NewMockOrderAccrualRepository creates a new mock instance.
func NewMockOrderAccrualRepository(ctrl *gomock.Controller) *MockOrderAccrualRepository {
	mock := &MockOrderAccrualRepository{ctrl: ctrl}
	mock.recorder = &MockOrderAccrualRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderAccrualRepository) EXPECT() *MockOrderAccrualRepositoryMockRecorder {
	return m.recorder
}

// GetOrderStatus mocks base method.
func (m *MockOrderAccrualRepository) GetOrderStatus(ctx context.Context, number string) (string, decimal.Decimal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderStatus", ctx, number)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(decimal.Decimal)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetOrderStatus indicates an expected call of GetOrderStatus.
func (mr *MockOrderAccrualRepositoryMockRecorder) GetOrderStatus(ctx, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderStatus", reflect.TypeOf((*MockOrderAccrualRepository)(nil).GetOrderStatus), ctx, number)
}

// MockOrderStatusRepository is a mock of OrderStatusRepository interface.
type MockOrderStatusRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderStatusRepositoryMockRecorder
	isgomock struct{}
}

// MockOrderStatusRepositoryMockRecorder is the mock recorder for MockOrderStatusRepository.
type MockOrderStatusRepositoryMockRecorder struct {
	mock *MockOrderStatusRepository
}

// NewMockOrderStatusRepository creates a new mock instance.
func NewMockOrderStatusRepository(ctrl *gomock.Controller) *MockOrderStatusRepository {
	mock := &MockOrderStatusRepository{ctrl: ctrl}
	mock.recorder = &MockOrderStatusRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderStatusRepository) EXPECT() *MockOrderStatusRepositoryMockRecorder {
	return m.recorder
}

// AddUserBalanceByID mocks base method.
func (m *MockOrderStatusRepository) AddUserBalanceByID(ctx context.Context, userID int64, add decimal.Decimal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserBalanceByID", ctx, userID, add)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserBalanceByID indicates an expected call of AddUserBalanceByID.
func (mr *MockOrderStatusRepositoryMockRecorder) AddUserBalanceByID(ctx, userID, add any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserBalanceByID", reflect.TypeOf((*MockOrderStatusRepository)(nil).AddUserBalanceByID), ctx, userID, add)
}

// BeginTx mocks base method.
func (m *MockOrderStatusRepository) BeginTx(ctx context.Context) (context.Context, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockOrderStatusRepositoryMockRecorder) BeginTx(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockOrderStatusRepository)(nil).BeginTx), ctx)
}

// CommitTx mocks base method.
func (m *MockOrderStatusRepository) CommitTx(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitTx", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitTx indicates an expected call of CommitTx.
func (mr *MockOrderStatusRepositoryMockRecorder) CommitTx(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitTx", reflect.TypeOf((*MockOrderStatusRepository)(nil).CommitTx), ctx)
}

// GetNewOrProcessingOrderNumbers mocks base method.
func (m *MockOrderStatusRepository) GetNewOrProcessingOrderNumbers(ctx context.Context, batchSize int) ([]*model.ProcessingOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNewOrProcessingOrderNumbers", ctx, batchSize)
	ret0, _ := ret[0].([]*model.ProcessingOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNewOrProcessingOrderNumbers indicates an expected call of GetNewOrProcessingOrderNumbers.
func (mr *MockOrderStatusRepositoryMockRecorder) GetNewOrProcessingOrderNumbers(ctx, batchSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNewOrProcessingOrderNumbers", reflect.TypeOf((*MockOrderStatusRepository)(nil).GetNewOrProcessingOrderNumbers), ctx, batchSize)
}

// RollbackTx mocks base method.
func (m *MockOrderStatusRepository) RollbackTx(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackTx", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RollbackTx indicates an expected call of RollbackTx.
func (mr *MockOrderStatusRepositoryMockRecorder) RollbackTx(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackTx", reflect.TypeOf((*MockOrderStatusRepository)(nil).RollbackTx), ctx)
}

// SetOrderStatus mocks base method.
func (m *MockOrderStatusRepository) SetOrderStatus(ctx context.Context, number, status string, accrual decimal.Decimal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetOrderStatus", ctx, number, status, accrual)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetOrderStatus indicates an expected call of SetOrderStatus.
func (mr *MockOrderStatusRepositoryMockRecorder) SetOrderStatus(ctx, number, status, accrual any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOrderStatus", reflect.TypeOf((*MockOrderStatusRepository)(nil).SetOrderStatus), ctx, number, status, accrual)
}
